GET http://localhost:5001/cloud-function-demo-c8898/us-central1/helloWorld

###
POST http://localhost:5001/cloud-function-demo-c8898/us-central1/addUser
Content-Type: application/json

{
    "name": "Saravanan S"
}

###

GET http://localhost:5001/cloud-function-demo-c8898/us-central1/addUser

###

DELETE  http://localhost:5001/cloud-function-demo-c8898/us-central1/addUser/hniVkgAvNt7FYtEXJkms


###
PUT   http://localhost:5001/cloud-function-demo-c8898/us-central1/addUser/hniVkgAvNt7FYtEXJkms
Content-Type: application/json

{
    "name": "Saravanan J S"
}

###
POST http://localhost:5001/cloud-function-demo-c8898/us-central1/authUser
Content-Type: application/json

{
    "email": "abcd@gmail.com",
    "password": "ram@123"
}